[world]
seed = "summit17"
name = "Summit Dev"
description = "Crown the Beast"
website = "https://github.com/provablegames"

[world.socials]
x = "https://x.com/provablegames"
github = "https://github.com/provablegames"

[namespace]
default = "savage_summit"

[writers]
"savage_summit" = [
    "savage_summit-summit_systems",
]